In [5]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=0)

print(newarr)


[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [8]:
x = np.zeros([3,3])
print(x)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [11]:
from numpy import random


print(x)

37


In [13]:
for i in range(100):
    x = random.randint(100)
    print(x)

80
59
47
29
0
40
62
40
98
36
44
77
51
54
87
62
46
27
63
73
54
60
79
22
47
93
70
51
68
95
25
48
28
62
32
85
28
86
80
2
10
63
47
16
24
96
18
23
97
98
61
93
25
60
7
65
95
8
1
95
79
45
16
29
77
43
3
54
28
66
12
42
41
89
38
6
72
73
28
68
3
77
27
61
17
5
40
64
56
23
97
8
47
44
84
79
70
15
17
57
